@include('include.header')
@include('include.header-bot')
@include('include.banner-top')
@include('include.signin')
@include('include.signup')
@include('include.slider')
@include('include.login')
@include('include.muahang')